
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Potion : Luban.BeanBase
{
    public Potion(JSONNode _buf) 
    {
        { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["PotionTag"].IsString) { throw new SerializationException(); }  PotionTag = _buf["PotionTag"]; }
        { if(!_buf["SpritePath"].IsString) { throw new SerializationException(); }  SpritePath = _buf["SpritePath"]; }
    }

    public static Potion DeserializePotion(JSONNode _buf)
    {
        return new Potion(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 魔药名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 魔药对应的道具合成tag组合
    /// </summary>
    public readonly string PotionTag;
    /// <summary>
    /// 图片路径
    /// </summary>
    public readonly string SpritePath;
   
    public const int __ID__ = -1898564173;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "PotionTag:" + PotionTag + ","
        + "SpritePath:" + SpritePath + ","
        + "}";
    }
}

}

