
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbPotion TbPotion {get; }
    public TbStoryNode TbStoryNode {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbPotion = new TbPotion(loader("tbpotion"));
        TbStoryNode = new TbStoryNode(loader("tbstorynode"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbPotion.ResolveRef(this);
        TbStoryNode.ResolveRef(this);
    }
}

}
