
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPotion
{
    private readonly System.Collections.Generic.Dictionary<int, Potion> _dataMap;
    private readonly System.Collections.Generic.List<Potion> _dataList;
    
    public TbPotion(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Potion>();
        _dataList = new System.Collections.Generic.List<Potion>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Potion _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Potion.DeserializePotion(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Potion> DataMap => _dataMap;
    public System.Collections.Generic.List<Potion> DataList => _dataList;

    public Potion GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Potion Get(int key) => _dataMap[key];
    public Potion this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

