
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbStoryNode
{
    private readonly System.Collections.Generic.Dictionary<int, StoryNode> _dataMap;
    private readonly System.Collections.Generic.List<StoryNode> _dataList;
    
    public TbStoryNode(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, StoryNode>();
        _dataList = new System.Collections.Generic.List<StoryNode>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            StoryNode _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = StoryNode.DeserializeStoryNode(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, StoryNode> DataMap => _dataMap;
    public System.Collections.Generic.List<StoryNode> DataList => _dataList;

    public StoryNode GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public StoryNode Get(int key) => _dataMap[key];
    public StoryNode this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

